const OK = 200;
const NOTFOUND = 404;
const BADREQUEST = 400;
const CREATED = 201;
const UPDATE = 202;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {OK, NOTFOUND, BADREQUEST, CREATED, UPDATE, INTERNAL_SERVER_ERROR};